# Generated by Django 4.2.20 on 2025-10-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact",
                    models.CharField(max_length=13, verbose_name="Client contact"),
                ),
                ("plate_number", models.CharField(max_length=10)),
                ("dimension", models.IntegerField()),
                (
                    "car_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Sedan", "sedan car"),
                            ("SUV", "SUV car"),
                            ("truck", "Truck motors"),
                        ],
                        default="N/A",
                        max_length=10,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
