# Generated by Django 4.2.20 on 2025-10-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="parking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parking_id", models.IntegerField()),
                ("time_in", models.TimeField()),
                ("time_out", models.TimeField()),
                ("status_pay", models.CharField(max_length=10)),
            ],
        ),
    ]
