# Generated by Django 4.2.20 on 2025-10-13 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_parking"),
    ]

    operations = [
        migrations.CreateModel(
            name="parking_lot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lot_id", models.IntegerField()),
                ("current_status", models.CharField(max_length=10)),
                ("lot_capacity", models.IntegerField()),
                (
                    "parking_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.parking"
                    ),
                ),
            ],
        ),
    ]
