# Generated by Django 4.2.20 on 2025-10-13 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_parking_lot"),
    ]

    operations = [
        migrations.CreateModel(
            name="parking_space",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parking_space_id", models.IntegerField()),
                (
                    "space_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BOX", "box parking"),
                            ("Angular", "angular parking"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("floor_number", models.IntegerField()),
                (
                    "plate_number",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.client"
                    ),
                ),
            ],
        ),
    ]
