# Generated by Django 4.2.20 on 2025-10-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_parking_space"),
    ]

    operations = [
        migrations.CreateModel(
            name="reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resevertion_number", models.IntegerField()),
                (
                    "type_of_reservation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BOX", "box parking"),
                            ("Angular", "angular parking"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("reservation_status", models.CharField(max_length=10)),
            ],
        ),
    ]
