# Generated by Django 5.2.7 on 2025-11-20 12:45

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_reservation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parking_space",
            name="parking_space_id",
        ),
        migrations.RemoveField(
            model_name="parking_space",
            name="plate_number",
        ),
        migrations.AddField(
            model_name="client",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="full_name",
            field=models.CharField(default="Unnamed Client", max_length=120),
        ),
        migrations.AddField(
            model_name="parking_space",
            name="dimension_limit",
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name="parking_space",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="parking_space",
            name="label",
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="blog.client",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="end_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="parking_slot",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservations",
                to="blog.parking_space",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="start_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="total_cost",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=8
            ),
        ),
        migrations.AlterField(
            model_name="parking_space",
            name="floor_number",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservation_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CONFIRMED", "Confirmed"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="resevertion_number",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
