# Generated by Django 5.2.7 on 2025-11-20 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_remove_parking_space_parking_space_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="parking_space",
            name="is_occupied",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="parking_space",
            name="parking_lot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spaces",
                to="blog.parking_lot",
            ),
        ),
        migrations.AlterField(
            model_name="parking_lot",
            name="current_status",
            field=models.CharField(default="Open", max_length=32),
        ),
        migrations.AlterField(
            model_name="parking_lot",
            name="lot_capacity",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name="parking_lot",
            name="parking_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.parking",
            ),
        ),
    ]
