# Generated by Django 4.2.20 on 2025-12-12 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_parking_space_is_occupied_parking_space_parking_lot_and_more"),
    ]

    operations = [
        migrations.RenameModel(old_name="parking_lot", new_name="ParkingLot"),
        migrations.RenameModel(old_name="parking_space", new_name="ParkingSpace"),
        migrations.RenameField(
            model_name="parkinglot",
            old_name="parking_id",
            new_name="parking",
        ),
        migrations.RenameField(
            model_name="reservation",
            old_name="resevertion_number",
            new_name="reservation_number",
        ),
        migrations.AlterField(
            model_name="client",
            name="dimension",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="client",
            name="car_type",
            field=models.CharField(
                blank=True,
                choices=[("Sedan", "Sedan"), ("SUV", "SUV"), ("Truck", "Truck")],
                default="N/A",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="type_of_reservation",
            field=models.CharField(
                blank=True,
                choices=[("BOX", "Box parking"), ("Angular", "Angular parking")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="parkingspace",
            name="dimension_limit",
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.AlterField(
            model_name="parkingspace",
            name="parking_lot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spaces",
                to="blog.parkinglot",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="parking_slot",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservations",
                to="blog.parkingspace",
            ),
        ),
        migrations.AlterModelOptions(
            name="client",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
            },
        ),
        migrations.AlterModelOptions(
            name="parking",
            options={"verbose_name": "Parking", "verbose_name_plural": "Parkings"},
        ),
        migrations.AlterModelOptions(
            name="parkinglot",
            options={
                "ordering": ["lot_id"],
                "verbose_name": "Parking lot",
                "verbose_name_plural": "Parking lots",
            },
        ),
        migrations.AlterModelOptions(
            name="parkingspace",
            options={
                "ordering": ["floor_number", "label"],
                "verbose_name": "Parking space",
                "verbose_name_plural": "Parking spaces",
            },
        ),
        migrations.AlterModelOptions(
            name="reservation",
            options={
                "ordering": ["-start_time"],
                "verbose_name": "Reservation",
                "verbose_name_plural": "Reservations",
            },
        ),
    ]
