# Generated by Django 4.2.20 on 2025-12-12 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_rename_models_and_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parkinglot",
            name="parking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lots",
                to="blog.parking",
            ),
        ),
        migrations.AlterField(
            model_name="parkingspace",
            name="space_type",
            field=models.CharField(
                blank=True,
                choices=[("BOX", "Box parking"), ("Angular", "Angular parking")],
                max_length=20,
                null=True,
            ),
        ),
    ]
